TASK:
  "classification"
INPUT:
  NUM_POINTS: 1024
  IN_CHANNELS: 6
  USE_NORMAL: True
MODEL:
  TYPE: "PN2MSG"
  PN2MSG:
    NUM_POINTS: (1024,)
    RADIUS: ((0.2, 0.3, 0.4),)
    NUM_SAMPLE: ((32, 48, 64),)
    GROUP_MLPS: (((64, 64, 16), (64, 64, 16), (64, 64, 29)),)
    GLOBAL_MLPS: (128, 1024)
    DROP_PROB: 0.3
DATASET:
  ROOT_DIR: "data/modelnet40/modelnet40_fewshot"
  TYPE: "ModelNetFewShot"
  NUM_CLASSES: 30
  TRAIN: ("train",)
  VAL: ("valid",)
  TEST: ("valid",)
SOLVER:
  BASE_LR: 0.001
  MAX_EPOCH: 250
  GAMMA: 0.7
  STEPS: (20, 40, 60, 80, 100, 120, 140, 160, 180, 200, 220, 240)
TRAIN:
  BATCH_SIZE: 32
  AUGMENTATION: ("PointCloudRotate", "PointCloudRotatePerturbation", "PointCloudScale", "PointCloudTranslate", "PointCloudJitter",)
  LOG_PERIOD: 50
  CHECKPOINT_PERIOD: 100
  VAL_PERIOD: 10
TEST:
  BATCH_SIZE: 32
  VOTE:
    ENABLE: False
    NUM_VIEW: 12
    SCORE_HEUR: ("logit",)
