TASK:
  "classification"
INPUT:
  NUM_POINTS: 1024
MODEL:
  TYPE: "POINTNET_FEWSHOT"
  POINTNET:
    DROPOUT_PROB: 0.3
    REG_WEIGHT: 0.032
DATASET:
  ROOT_DIR: "data/modelnet40_fewshot"
  TYPE: "MODELNET_FEWSHOT"
  NUM_CLASSES: 30
  TRAIN: ("train",)
  VAL: ("valid",)
  TEST: ("valid",)
SOLVER:
  BASE_LR: 0.001
  MAX_EPOCH: 250
  GAMMA: 0.7
  STEPS: (20, 40, 60, 80, 100, 120, 140, 160, 180, 200, 220, 240)
TRAIN:
  BATCH_SIZE: 32
  AUGMENTATION: ("PointCloudRotate", ("PointCloudRotatePerturbation",0.06, 0.18), "PointCloudScale", "PointCloudTranslate", "PointCloudJitter",)
  LOG_PERIOD: 50
  CHECKPOINT_PERIOD: 100
  VAL_PERIOD: 1
TEST:
  BATCH_SIZE: 32
  VOTE:
    ENABLE: True
    NUM_VIEW: 12
    SCORE_HEUR: ("logit",)
