TASK:
  "classification"
INPUT:
  NUM_POINTS: 1024
MODEL:
  TYPE: "POINTNET_FEWSHOT"
  WEIGHT: "outputs/fewshot/modelnet/pointnet_cls/model_best.pth"
  POINTNET:
    DROPOUT_PROB: 0.3
    REG_WEIGHT: 0.032
DATASET:
  ROOT_DIR: "data/modelnet40_fewshot"
  TYPE: "MODELNET_FEWSHOT"
  NUM_CLASSES: 10
  TRAIN: ("support",)
  VAL: ("target",)
  TEST: ("target",)
  FEWSHOT:
    K: 1
    CROSS_INDEX: 0
SOLVER:
  BASE_LR: 0.001
  MAX_EPOCH: 250
  GAMMA: 0.7
  STEPS: (20, 40, 60, 80, 100, 120, 140, 160, 180, 200, 220, 240)
TRAIN:
  BATCH_SIZE: 10
  AUGMENTATION: ("PointCloudRotate", ("PointCloudRotatePerturbation",0.06, 0.18), "PointCloudScale", "PointCloudTranslate", "PointCloudJitter",)
  LOG_PERIOD: 50
  CHECKPOINT_PERIOD: 1000
  VAL_PERIOD: 10
TEST:
  BATCH_SIZE: 10
  VOTE:
    ENABLE: True
    NUM_VIEW: 12
    SCORE_HEUR: ("logit",)
