TASK:
  "classification"
INPUT:
  NUM_POINTS: 1024
MODEL:
  TYPE: "PN2SSG"
  PN2SSG:
    NUM_CENTROIDS: (1024,)
    RADIUS: (0.3,)
    NUM_NEIGHBOURS: (48,)
    SA_CHANNELS: ((64,64,61),)
    LOCAL_CHANNELS: (128, 1024)
    DROPOUT_PROB: 0.3
DATASET:
  ROOT_DIR: "/home/rayc/Projects/shaper/data/shapenet55_h5/shapenet55_fewshot"
  TYPE: "SHAPENET55_FEWSHOT"
  NUM_CLASSES: 44
  TRAIN: ("train",)
  VAL: ("valid",)
  TEST: ("valid",)
SOLVER:
  BASE_LR: 0.001
  MAX_EPOCH: 250
  GAMMA: 0.7
  STEPS: (20, 40, 60, 80, 100, 120, 140, 160, 180, 200, 220, 240)
TRAIN:
  BATCH_SIZE: 16
  AUGMENTATION: ("PointCloudRotate", "PointCloudRotatePerturbation", "PointCloudScale", "PointCloudTranslate", "PointCloudJitter",)
  LOG_PERIOD: 50
  CHECKPOINT_PERIOD: 50
  VAL_PERIOD: 1
TEST:
  BATCH_SIZE: 16
