TASK:
  "classification"
INPUT:
  NUM_POINTS: 1024
MODEL:
  TYPE: "PN2MSG"
  PN2MSG:
    NUM_CENTROIDS: (1024,)
    RADIUS: ((0.2, 0.3, 0.4),)
    NUM_NEIGHBOURS: ((32, 48, 64),)
    SA_CHANNELS: (((64, 64, 16), (64, 64, 16), (64, 64, 29)),)
    LOCAL_CHANNELS: (128, 1024)
    DROPOUT_PROB: 0.3
DATASET:
  ROOT_DIR: "/home/rayc/Projects/shaper/data/shapenet55_h5/shapenet55_fewshot"
  TYPE: "SHAPENET55_FEWSHOT"
  NUM_CLASSES: 44
  TRAIN: ("train",)
  VAL: ("valid",)
  TEST: ("valid",)
SOLVER:
  BASE_LR: 0.001
  MAX_EPOCH: 250
  GAMMA: 0.7
  STEPS: (20, 40, 60, 80, 100, 120, 140, 160, 180, 200, 220, 240)
TRAIN:
  BATCH_SIZE: 32
  AUGMENTATION: ("PointCloudRotate", "PointCloudRotatePerturbation", "PointCloudScale", "PointCloudTranslate", "PointCloudJitter",)
  LOG_PERIOD: 50
  CHECKPOINT_PERIOD: 50
  VAL_PERIOD: 1
TEST:
  BATCH_SIZE: 32
