TASK:
  "classification"
INPUT:
  NUM_POINTS: 1024
MODEL:
  TYPE: "PNS2CNN"
  PNS2CNN:
    NUM_POINTS: 1024
    RADIUS_LIST: (0.3, )
    NUM_SAMPLE_LIST: (48, )
    BAND_WIDTH_IN_LIST: (16,)
    FEATURE_CHANNELS_LIST: ((64, 64, 61),)
    BAND_WIDTH_LIST: ((16, 8, 8),)
    GLOBAL_CHANNELS: (128, 1024)
    DROP_PROB: 0.3
    TRANSFORM_XYZ: False
DATASET:
  ROOT_DIR: "data/modelnet40/modelnet40_fewshot"
  TYPE: "ModelNetFewShot"
  NUM_CLASSES: 30
  TRAIN: ("train",)
  VAL: ("valid",)
  TEST: ("valid",)
SOLVER:
  BASE_LR: 0.001
  MAX_EPOCH: 250
  GAMMA: 0.7
  STEPS: (20, 40, 60, 80, 100, 120, 140, 160, 180, 200, 220, 240)
TRAIN:
  BATCH_SIZE: 32
  AUGMENTATION: ("PointCloudRotate", ("PointCloudRotatePerturbation",0.06, 0.18), "PointCloudScale", "PointCloudTranslate", "PointCloudJitter",)
  LOG_PERIOD: 50
  CHECKPOINT_PERIOD: 100
  VAL_PERIOD: 1
TEST:
  BATCH_SIZE: 32
