TASK:
  "part_segmentation"
AUTO_RESUME: False
MODEL:
  TYPE: "DGCNN"
INPUT:
  NUM_POINTS: 2048
DATASET:
  ROOT_DIR: "data/shapenet_hdf5"
  TYPE: "ShapeNetH5"
  NUM_CLASSES: 16
  NUM_SEG_CLASSES: 50
  TRAIN: ("train",)
  VAL: ("val",)
  TEST: ("test",)
SOLVER:
  TYPE: "Adam"
  BASE_LR: 0.003
SCHEDULER:
  TYPE: "StepLR"
  StepLR:
    gamma: 0.7
    step_size: 20
  MAX_EPOCH: 250
TRAIN:
  BATCH_SIZE: 16 
  LOG_PERIOD: 50
  VAL_PERIOD: 1
TEST:
  BATCH_SIZE: 16
  VOTE:
    ENABLE: False
