TASK:
  "classification"
MODEL:
  TYPE: "DGCNNCOR"
  DGCNN:
    LABEL_SMOOTHING: 0.2
    K: 20
INPUT:
  NUM_POINTS: 1024
DATASET:
  ROOT_DIR: "data/modelnet40"
  TYPE: "ModelNet"
  NUM_CLASSES: 40
  TRAIN: ("train",)
  VAL: ("test",)
  TEST: ("test",)
SOLVER:
  BASE_LR: 0.001
  MAX_EPOCH: 250
  GAMMA: 0.7
  STEPS: (20, 40, 60, 80, 100, 120, 140, 160, 180, 200, 220, 240)
TRAIN:
  BATCH_SIZE: 32
  AUGMENTATION: ("PointCloudRotate", "PointCloudJitter", "PointCloudScale", "PointCloudRotatePerturbation", "PointCloudTranslate", )
  LOG_PERIOD: 50
  CHECKPOINT_PERIOD: 20
  VAL_PERIOD: 1
TEST:
  BATCH_SIZE: 32
OUTPUT_DIR: "@/reproduce"