AUTO_RESUME: true
DATASET:
  ROOT_DIR: data/big/hier_ins_seg_100K_h5/Bag_small
  TEST: ("test",)
  TRAIN: ("train",)
  TYPE: PartNet
  VAL: ("val",)
INPUT:
  NUM_POINTS: 3500
MODEL:
  DGCNN:
    DROPOUT_PROB: 0.0
    K: 80
  META_DATA: 20
  NUM_INS_MASKS: 400
  PROP_NORMALIZATION: BN
  SEG_NORMALIZATION: BN
  TYPE: DGCNN
SCHEDULER:
  MAX_EPOCH: 400
  StepLR:
    gamma: 0.7
    step_size: 20
  TYPE: StepLR
SOLVER:
  BASE_LR: 0.003
  TYPE: Adam
TASK: part_instance_segmentation
TEST:
  BATCH_SIZE: 1
  NUM_ZOOM_ITERATION: 5
  VIS_DIR: visu_test2.0
TRAIN:
  AUGMENTATION: ("PointCloudRotate",  "PointCloudScale", "PointCloudRotatePerturbation",
    "PointCloudTranslate", )
  BATCH_SIZE: 5
  CHECKPOINT_PERIOD: 10
  CHECKPOINT_START: 350
  LOG_PERIOD: 50
  NUM_ZOOM_ITERATION: 6
  VAL_PERIOD: 0
