TASK:
  "part_instance_segmentation"
AUTO_RESUME: False
MODEL:
  TYPE: "DGCNN"
  NORMALIZATION: "BN"
  NUM_INS_MASKS: 400
  DGCNN:
      K: 20
      DROPOUT_PROB: 0.0
INPUT:
  NUM_POINTS: 2500
DATALOADER:
  NUM_WORKERS: 4
DATASET:
  ROOT_DIR: "data/big/hier_ins_seg_100K_h5/Mug_small"
  TYPE: "PartNet"
  TRAIN: ("train",)
  VAL: ("val",)
  TEST: ("test",)
SOLVER:
  TYPE: "Adam"
  BASE_LR: 0.003
SCHEDULER:
  TYPE: "StepLR"
  StepLR:
    gamma: 0.7
    step_size: 20
  MAX_EPOCH: 500
TRAIN:
  BATCH_SIZE: 8
  CHECKPOINT_PERIOD: 20
  LOG_PERIOD: 10
  VAL_PERIOD: 10
  AUGMENTATION: ("PointCloudRotate", "PointCloudRotatePerturbation","PointCloudScale", "PointCloudTranslate")
TEST:
  BATCH_SIZE: 16
  #AUGMENTATION: ("PointCloudRotate",)
  VIS_DIR: 'visu_test'
