TASK:
  "foveal_part_instance_segmentation"
AUTO_RESUME: True
MODEL:
  TYPE: "DGCNN"
  PROP_NORMALIZATION: "BN"
  SEG_NORMALIZATION: "BN"
  NUM_INS_MASKS: 4
  META_DATA: 20
  DGCNN:
      K: 20
      DROPOUT_PROB: 0.0
INPUT:
  NUM_POINTS: 2500
DATASET:
  ROOT_DIR: "data/big/hier_ins_seg_100K_h5/Mug_small" 
  TYPE: "PartNet"
  TRAIN: ("train",)
  VAL: ("val",)
  TEST: ("test",)
SOLVER:
  TYPE: "Adam"
  BASE_LR: 0.003
SCHEDULER:
  TYPE: "StepLR"
  StepLR:
    gamma: 0.7
    step_size: 20
  MAX_EPOCH: 500
TRAIN:
  BATCH_SIZE: 6
  CHECKPOINT_PERIOD: 10
  LOG_PERIOD: 50
  VAL_PERIOD: 0
  AUGMENTATION: ("PointCloudRotate",  "PointCloudScale", "PointCloudRotatePerturbation", "PointCloudTranslate", )
  NUM_ZOOM_ITERATION: 12
TEST:
  BATCH_SIZE: 1
  NUM_ZOOM_ITERATION: 12
  VIS_DIR: 'visu_test'
