TASK:
  "classification"
MODEL:
  TYPE: "POINTNET"
  POINTNET:
    DROPOUT_PROB: 0.3
    REG_WEIGHT: 0.032
INPUT:
  NUM_POINTS: 1024
DATASET:
  ROOT_DIR: "data/modelnet40"
  TYPE: "ModelNetH5"
  NUM_CLASSES: 40
  TRAIN: ("train",)
  VAL: ("test",)
  TEST: ("test",)
SOLVER:
  TYPE: "Adam"
  BASE_LR: 0.001
SCHEDULER:
  TYPE: "StepLR"
  StepLR:
    gamma: 0.7
    step_size: 20
  MAX_EPOCH: 250
TRAIN:
  BATCH_SIZE: 32
  AUGMENTATION: ("PointCloudRotate", "PointCloudJitter",)
  LOG_PERIOD: 50
  VAL_PERIOD: 1
TEST:
  BATCH_SIZE: 32
  VOTE:
    NUM_VOTE: 12
    TYPE: "MULTI_VIEW"