TASK:
  "part_segmentation"
MODEL:
  TYPE: "POINTNET"
INPUT:
  NUM_POINTS: 2048
#  NUM_POINTS: 3000
DATASET:
  ROOT_DIR: "data/shapenet_hdf5"
  TYPE: "ShapeNetH5"
  #  ROOT_DIR: "data/shapenet"
  #  TYPE: "ShapeNet"
  NUM_CLASSES: 16
  NUM_SEG_CLASSES: 50
  TRAIN: ("train",)
  VAL: ("val",)
  TEST: ("test",)
SOLVER:
  TYPE: "Adam"
  BASE_LR: 0.001
SCHEDULER:
  TYPE: "MultiStepLR"
  MultiStepLR:
    gamma: 0.5
    milestones: (20, 40, 60, 80, 100, 120)
  MAX_EPOCH: 200
TRAIN:
  BATCH_SIZE: 32
  LOG_PERIOD: 50
  VAL_PERIOD: 1
TEST:
  BATCH_SIZE: 32
  VOTE:
    ENABLE: False