TASK:
  "part_segmentation"
MODEL:
  TYPE: "PN2SSG"
INPUT:
  IN_CHANNELS: 6
  NUM_POINTS: 2048
  USE_NORMAL: True
DATASET:
  ROOT_DIR: "data/shapenet_normal"
  TYPE: "ShapeNetNormal"
  NUM_CLASSES: 16
  NUM_SEG_CLASSES: 50
  TRAIN: ("train",)
  VAL: ("val",)
  TEST: ("test",)
DATALOADER:
  # ShapeNetNormal has many small files.
  NUM_WORKERS: 8
SOLVER:
  BASE_LR: 0.001
  MAX_EPOCH: 200
  GAMMA: 0.5
  STEPS: (20, 40, 60, 80, 100, 120)
TRAIN:
  BATCH_SIZE: 32
  AUGMENTATION: ("PointCloudRotate", ("PointCloudJitter", 0.01, 0.05),)
  SEG_AUGMENTATION: ("PointCloudShuffle", "PointCloudRandomInputDropout")
  LOG_PERIOD: 50
  VAL_PERIOD: 1
TEST:
  BATCH_SIZE: 32
  VOTE:
    ENABLE: False