TASK:
  "part_segmentation"
INPUT:
  NUM_POINTS: 1024
MODEL:
  TYPE: "PointNet"
  POINTNET:
    DROPOUT_PROB_CLS: 0.3
    DROPOUT_PROB_SEG: 0.2
    REG_WEIGHT: 1e-3
    SEG_WEIGHT: 1.  # classification loss is not taken into account (cls_weight = 1 - seg_weight)
    STEM_CHANNELS: (64, 128, 128)
    LOCAL_CHANNELS: (512, 2048)
    GLOBAL_CHANNELS: (256, 256)
    MLP_SEG_CHANNELS: (256, 256, 128)
DATASET:
  ROOT_DIR: "data/shapenet"
  TYPE: "ShapeNet"
  NUM_CATEGORIES: 16
  NUM_CLASSES: 50
  TRAIN: ("train",)
  VAL: ("val",)
  TEST: ("test",)
  LOAD_SEG: True
SOLVER:
  BASE_LR: 0.001
  MAX_EPOCH: 250
  GAMMA: 0.7
  STEPS: (20, 40, 60, 80, 100, 120, 140, 160, 180, 200, 220, 240)
TRAIN:
  BATCH_SIZE: 32
  AUGMENTATION: ("PointCloudRotate", ("PointCloudJitter", 0.01, 0.05),)
  LOG_PERIOD: 50
  CHECKPOINT_PERIOD: 20
  VAL_PERIOD: 1
TEST:
  BATCH_SIZE: 32
  VOTE:
    ENABLE: True
    NUM_VIEW: 12
    SCORE_HEUR: ("logit",)
  VIS_DIR: "@/vis_error_key_pts"