TASK:
  "semantic_segmentation"
INPUT:
  IN_CHANNELS: 3
  NUM_POINTS: 1024
MODEL:
  TYPE: "PN2SSG"
DATASET:
  ROOT_DIR: "data/scannet"
  TYPE: "ScanNet"
  NUM_SEG_CLASSES: 21
  TRAIN: ("train",)
  VAL: ("val",)
  TEST: ("test",)
SOLVER:
  TYPE: "Adam"
  BASE_LR: 0.001
SCHEDULER:
  TYPE: "MultiStepLR"
  MultiStepLR:
    gamma: 0.5
    milestones: (20, 40, 60, 80, 100, 120)
  MAX_EPOCH: 200
TRAIN:
  BATCH_SIZE: 32
  LOG_PERIOD: 50
  CHECKPOINT_PERIOD: 20
  VAL_PERIOD: 1
TEST:
  BATCH_SIZE: 32
  VOTE:
    ENABLE: True
  VIS_DIR: "@/vis_error_key_pts"
