TASK:
  "classification"
AUTO_RESUME: False
INPUT:
  NUM_POINTS: 1024
MODEL:
  TYPE: "PointNet"
DATASET:
  ROOT_DIR: "data/modelnet40"
  TYPE: "ModelNet"
  NUM_CLASSES: 40
  TRAIN: ("train",)
  VAL: ("test",)
  TEST: ("test",)
DATALOADER:
  NUM_WORKERS: 8
SOLVER:
  BASE_LR: 0.002
  MAX_EPOCH: 250
  GAMMA: 0.8
  STEPS: (20, 40, 60, 80, 120, 140, 160, 180, 200, 220)
TRAIN:
  BATCH_SIZE: 64
  AUGMENTATION: ("PointCloudRotate", ("PointCloudRotatePerturbation",0.1, 0.2), "PointCloudTranslate", "PointcloudScale", "PointCloudJitter",)
  VAL_PERIOD: 1
TEST:
  BATCH_SIZE: 64
OUTPUT_DIR: "@"