TASK:
  "classification"
INPUT:
  NUM_POINTS: 1024
MODEL:
  TYPE: "PN2SSG"
DATASET:
  ROOT_DIR: "data/modelnet40"
  TYPE: "ModelNet"
  NUM_CLASSES: 40
  TRAIN: ("train",)
  VAL: ("test",)
  TEST: ("test",)
DATALOADER:
  NUM_WORKERS: 4
SOLVER:
  BASE_LR: 0.001
  MAX_EPOCH: 251
  GAMMA: 0.7
  STEPS: (20, 40, 60, 80, 120, 140, 160, 180, 200, 220)
TRAIN:
  BATCH_SIZE: 16
  AUGMENTATION: ("PointCloudRotate", ("PointCloudRotatePerturbation",0.06, 0.18), "PointCloudScale", "PointCloudTranslate", "PointCloudJitter",)
  LOG_PERIOD: 50
  CHECKPOINT_PERIOD: 20
  VAL_PERIOD: 1
TEST:
  BATCH_SIZE: 16