TASK:
  "part_instance_segmentation"
AUTO_RESUME: False
MODEL:
  TYPE: "PN2SSG"
  NORMALIZATION: "GN"
  NUM_INS_MASKS: 6
INPUT:
  IN_CHANNELS: 3
  NUM_POINTS: 10000 
DATASET:
  ROOT_DIR: "data/big/hier_ins_seg_100K_h5/Door/point2group_level2"
  TYPE: "PartNet"
  TRAIN: ("train", )
  VAL: ("val",)
  TEST: ("test",)
DATALOADER:
  NUM_WORKERS: 8
SOLVER:
  TYPE: "Adam"
  BASE_LR: 0.001
SCHEDULER:
  TYPE: "MultiStepLR"
  MultiStepLR:
    gamma: 0.5
    milestones: (20, 40, 60, 80, 100, 120)
  MAX_EPOCH: 10000
TRAIN:
  BATCH_SIZE: 16
  #AUGMENTATION: ("PointCloudRotate", "PointCloudJitter",)
  #SEG_AUGMENTATION: ("PointCloudShuffle",)
  LOG_PERIOD: 50
  VAL_PERIOD: 10
TEST:
  BATCH_SIZE: 32
  VIS_DIR: 'visu'
