TASK:
  "part_segmentation"
MODEL:
  TYPE: "PN2SSG"
  NORMALIZATION: "GN"
INPUT:
  IN_CHANNELS: 6
  NUM_POINTS: 2048
  USE_NORMAL: True
DATASET:
  ROOT_DIR: "data/shapenet_normal"
  TYPE: "ShapeNetNormal"
  NUM_CLASSES: 16
  NUM_SEG_CLASSES: 50
  TRAIN: ("train", "val",)
  VAL: ()
  TEST: ("test",)
DATALOADER:
  NUM_WORKERS: 8
SOLVER:
  TYPE: "Adam"
  BASE_LR: 0.001
SCHEDULER:
  TYPE: "MultiStepLR"
  MultiStepLR:
    gamma: 0.5
    milestones: (20, 40, 60, 80, 100, 120)
  MAX_EPOCH: 200
TRAIN:
  BATCH_SIZE: 16
  AUGMENTATION: ("PointCloudRotate", "PointCloudJitter",)
  SEG_AUGMENTATION: ("PointCloudShuffle",)
  LOG_PERIOD: 50
  VAL_PERIOD: 1
TEST:
  BATCH_SIZE: 32
