TASK:
  "classification"
MODEL:
  TYPE: "PointNet"
DATASET:
  TYPE: "ModelNet"
  NUM_CLASSES: 40
  TRAIN: ("train",)
  TEST: ("test",)
DATALOADER:
  NUM_WORKERS: 1
TRAIN:
  BATCH_SIZE: 32
TEST:
  BATCH_SIZE: 32
OUTPUT_DIR: "@"