TASK:
  "classification"
INPUT:
  NUM_POINTS: 1024
MODEL:
  TYPE: "PointNet"
  POINTNET:
    DROPOUT_PROB: 0.3
    REG_WEIGHT: 128.0
DATASET:
  ROOT_DIR: "data/modelnet40"
  TYPE: "ModelNet"
  NUM_CLASSES: 40
  SHAPE_NAME_PATH: "data/modelnet40/shape_names.txt"
  TRAIN: ("train",)
  VAL: ("test",)
  TEST: ("test",)
DATALOADER:
  NUM_WORKERS: 4
SOLVER:
  BASE_LR: 0.001
  MAX_EPOCH: 250
  GAMMA: 0.8
  STEPS: (20, 40, 60, 80, 120, 140, 160, 180, 200, 220)
TRAIN:
  BATCH_SIZE: 32
  AUGMENTATION: ("PointCloudRotate", ("PointCloudRotatePerturbation",0.06, 0.18), "PointCloudTranslate", "PointCloudScale", "PointCloudJitter",)
  LOG_PERIOD: 50
  CHECKPOINT_PERIOD: 20
  VAL_PERIOD: 1
TEST:
  BATCH_SIZE: 32
  VISUAL: True
  PIC_PATH: "outputs/wrong_pts"
  TYPE: "Vote"
  VOTE:
    NUMBER: 2
    TYPE: ["Logits", "Softmax", "Label"]
OUTPUT_DIR: "@"