TASK:
  "classification"
INPUT:
  NUM_POINTS: 1024
MODEL:
  TYPE: "PN2SSG"
DATASET:
  ROOT_DIR: "data/modelnet40"
  TYPE: "ModelNet"
  NUM_CLASSES: 40
  TRAIN: ("train",)
  VAL: ("test",)
  TEST: ("test",)
SOLVER:
  BASE_LR: 0.001
  MAX_EPOCH: 250
  GAMMA: 0.7
  STEPS: (20, 40, 60, 80, 100, 120, 140, 160, 180, 200, 220, 240)
TRAIN:
  BATCH_SIZE: 16
  AUGMENTATION: ("PointCloudRotate", "PointCloudRotatePerturbation", "PointCloudScale", "PointCloudTranslate", "PointCloudJitter", "PointCloudShuffle")
  LOG_PERIOD: 50
  VAL_PERIOD: 1
TEST:
  BATCH_SIZE: 16
  # Important to shuffle points during test
  AUGMENTATION: ("PointCloudShuffle",)
  VOTE:
    ENABLE: True
    NUM_VIEW: 12
    SCORE_HEUR: ("logit",)