TASK:
  "classification"
INPUT:
  NUM_POINTS: 1024
MODEL:
  TYPE: "PointNet"
DATASET:
  ROOT_DIR: "data/shapenet"
  TYPE: "ShapeNet"
  NUM_CLASSES: 16
  TRAIN: ("train",)
  TEST: ("test",)
TRAIN:
  BATCH_SIZE: 32
TEST:
  BATCH_SIZE: 32
OUTPUT_DIR: "@"