from shaper.config.classification import _C
from yacs.config import CfgNode as CN

_C.COMPARE_NET = CN()
_C.COMPARE_NET.MLPS = (256, 64, 16)
_C.COMPARE_NET.DROP_PROB = 0.0
_C.COMPARE_NET.DIRECT_PRED_WEIGHT = 1.0

_C.DATASET.COMPARE = CN()

_C.DATASET.COMPARE.CLASS_NUM_PER_BATCH = 10
_C.DATASET.COMPARE.BATCH_SUPPORT_NUM_PER_CLASS = 1
_C.DATASET.COMPARE.NUM_PER_CLASS = 1
_C.DATASET.COMPARE.CROSS_NUM = 0
_C.DATASET.COMPARE.TRAIN_BATCH_TARGET_NUM = 8
_C.DATASET.COMPARE.VAL_BATCH_TARGET_NUM = 1
_C.DATASET.COMPARE.TEST_BATCH_TARGET_NUM = 1

_C.TRAIN.LOAD_PRETRAIN = False
# Freeze layers other than classifier

_C.TRAIN.FREEZE_PARAMS = ()
