TASK:
  "classification"
INPUT:
  NUM_POINTS: 1024
MODEL:
  TYPE: "PointNet"
  WEIGHT: "/home/rayc/Projects/shaper/outputs/modelnet/comparenet/pointnet/pointnet_train_cls/model_250.pth"
  POINTNET:
    DROPOUT_PROB: 0.0
DATASET:
  ROOT_DIR: "data/modelnet40/modelnet40_fewshot"
  TYPE: "ModelNetCompare"
  NUM_CLASSES: 10
  TRAIN: ("support",)
  VAL: ("target",)
  TEST: ("target",)
  COMPARE:
    TRAIN_BATCH_TARGET_NUM: 10
    NUM_PER_CLASS: 1
    CROSS_NUM: 0
SOLVER:
  BASE_LR: 0.001
  MAX_EPOCH: 250
  GAMMA: 0.7
  STEPS: (20, 40, 60, 80, 100, 120, 140, 160, 180, 200, 220, 240)
TRAIN:
  LOAD_PRETRAIN: True
  AUGMENTATION: ("PointCloudRotate", ("PointCloudRotatePerturbation",0.06, 0.18), "PointCloudScale", "PointCloudTranslate", "PointCloudJitter",)
  LOG_PERIOD: 50
  CHECKPOINT_PERIOD: 100
  VAL_PERIOD: 10
TEST:
  LOG_PERIOD: 100
OUTPUT_DIR: "@"
