from shaper.config.classification import _C
from yacs.config import CfgNode as CN

_C.PROTO_NET = CN()
_C.PROTO_NET.DIRECT_PRED_WEIGHT = 1.0

_C.DATASET.PROTO = CN()

_C.DATASET.PROTO.CLASS_NUM_PER_BATCH = 10
_C.DATASET.PROTO.BATCH_SUPPORT_NUM_PER_CLASS = 5
_C.DATASET.PROTO.NUM_PER_CLASS = 1
_C.DATASET.PROTO.CROSS_NUM = 0
_C.DATASET.PROTO.TRAIN_BATCH_TARGET_NUM = 8
_C.DATASET.PROTO.VAL_BATCH_TARGET_NUM = 1
_C.DATASET.PROTO.TEST_BATCH_TARGET_NUM = 1

_C.TRAIN.LOAD_PRETRAIN = False
# Freeze layers other than classifier

_C.TRAIN.FREEZE_PARAMS = ()
