from shaper.config.classification import _C
from yacs.config import CfgNode as CN

_C.HISTO_NET = CN()
_C.HISTO_NET.DIRECT_PRED_WEIGHT = 1.0
_C.HISTO_NET.MODE = "max"
_C.HISTO_NET.NUM_STEPS = 11

_C.DATASET.HISTO = CN()

_C.DATASET.HISTO.CLASS_NUM_PER_BATCH = 10
_C.DATASET.HISTO.BATCH_SUPPORT_NUM_PER_CLASS = 5
_C.DATASET.HISTO.NUM_PER_CLASS = 1
_C.DATASET.HISTO.CROSS_NUM = 0
_C.DATASET.HISTO.TRAIN_BATCH_TARGET_NUM = 8
_C.DATASET.HISTO.VAL_BATCH_TARGET_NUM = 1
_C.DATASET.HISTO.TEST_BATCH_TARGET_NUM = 1

_C.TRAIN.LOAD_PRETRAIN = False
# Freeze layers other than classifier

_C.TRAIN.FREEZE_PARAMS = ()
