TASK:
  "classification"
INPUT:
  NUM_POINTS: 1024
MODEL:
  TYPE: "PointNet"
  POINTNET:
    DROPOUT_PROB: 0.3
    WITH_TRANSFORM: False
DATASET:
  ROOT_DIR: "data/shapenetcore"
  TYPE: "ShapeNetFewShot"
  NUM_CLASSES: 12
  TRAIN: ("train",)
  VAL: ("val",)
  TEST: ("val",)
DATALOADER:
  NUM_WORKERS: 16
SOLVER:
  BASE_LR: 0.001
  MAX_EPOCH: 250
  GAMMA: 0.7
  STEPS: (20, 40, 60, 80, 100, 120, 140, 160, 180, 200, 220, 240)
TRAIN:
  BATCH_SIZE: 32
  AUGMENTATION: ("PointCloudRotate", ("PointCloudRotatePerturbation",0.06, 0.18), "PointCloudScale", "PointCloudTranslate", "PointCloudJitter",)
  LOG_PERIOD: 50
  CHECKPOINT_PERIOD: 20
  VAL_PERIOD: 1
TEST:
  BATCH_SIZE: 32
