TASK:
  "classification"
INPUT:
  NUM_POINTS: 1024
  IN_CHANNELS: 6
  USE_NORMAL: True
MODEL:
  TYPE: "PN2SSG"
  PN2SSG:
    NUM_POINTS: (1024,)
    RADIUS: (0.3,)
    NUM_SAMPLE: (48,)
    GROUP_MLPS: ((64,64,61),)
    GLOBAL_MLPS: (128, 1024)
    DROP_PROB: 0.3
DATASET:
  ROOT_DIR: "data/modelnet40/modelnet40_fewshot"
  TYPE: "ModelNetFewShot"
  NUM_CLASSES: 30
  TRAIN: ("train",)
  VAL: ("valid",)
  TEST: ("valid",)
SOLVER:
  BASE_LR: 0.001
  MAX_EPOCH: 250
  GAMMA: 0.7
  STEPS: (20, 40, 60, 80, 100, 120, 140, 160, 180, 200, 220, 240)
TRAIN:
  BATCH_SIZE: 8
  AUGMENTATION: ("PointCloudRotate", "PointCloudRotatePerturbation", "PointCloudScale", "PointCloudTranslate", "PointCloudJitter",)
  LOG_PERIOD: 50
  CHECKPOINT_PERIOD: 100
  VAL_PERIOD: 10
TEST:
  BATCH_SIZE: 8
