TASK:
  "classification"
INPUT:
  NUM_POINTS: 1024
MODEL:
  TYPE: "POINTNET"
PROTO_NET:
  DIRECT_PRED_WEIGHT: 0.0
DATASET:
  ROOT_DIR: "data/modelnet40/modelnet40_fewshot"
  TYPE: "ModelNetProto"
  NUM_CLASSES: 30
  TRAIN: ("train",)
  VAL: ("valid",)
  TEST: ("valid",)
  PROTO:
    BATCH_SUPPORT_NUM_PER_CLASS: 5
SOLVER:
  BASE_LR: 0.001
  MAX_EPOCH: 250
  GAMMA: 0.7
  STEPS: (20, 40, 60, 80, 100, 120, 140, 160, 180, 200, 220, 240)
TRAIN:
  AUGMENTATION: ("PointCloudRotate", "PointCloudRotatePerturbation", "PointCloudScale", "PointCloudTranslate", "PointCloudJitter",)
  LOG_PERIOD: 50
  CHECKPOINT_PERIOD: 100
  VAL_PERIOD: 1
TEST:
  LOG_PERIOD: 100

