TASK:
  "classification"
INPUT:
  NUM_POINTS: 1024
MODEL:
  TYPE: "DGCNNFewShot"
  WEIGHT: "/home/rayc/Projects/shaper/outputs/few_shot/dgcnn_fewshot_cls/model_best.pth"
  DGCNN:
    K: 20
DATASET:
  ROOT_DIR: "data/modelnet40/modelnet40_fewshot"
  TYPE: "ModelNetFewShot"
  NUM_CLASSES: 10
  TRAIN: ("support",)
  VAL: ("target",)
  TEST: ("target",)
  FEW_SHOT:
    NUM_PER_CLASS: 1
    CROSS_NUM: 0
SOLVER:
  BASE_LR: 0.001
  MAX_EPOCH: 500
  GAMMA: 0.7
  STEPS: (40, 80, 120, 160, 200, 240, 280, 320, 360, 400, 440, 480)
TRAIN:
  LOAD_PRETRAIN: True
  BATCH_SIZE: 10
  AUGMENTATION: ("PointCloudRotate", "PointCloudRotatePerturbation", "PointCloudScale", "PointCloudTranslate", "PointCloudJitter",)
  LOG_PERIOD: 50
  CHECKPOINT_PERIOD: 50
  VAL_PERIOD: 10
TEST:
  BATCH_SIZE: 10
  LOG_PERIOD: 50
