TASK:
  "classification"
INPUT:
  NUM_POINTS: 1024
MODEL:
  TYPE: "PointNetFewShot"
  WEIGHT: "/home/rayc/Projects/shaper/outputs/few_shot/pointnet_fewshot_cls/pn_fewshot/model_target.pth"
  POINTNET:
    DROPOUT_PROB: 0.5
    REG_WEIGHT: 0.032
DATASET:
  ROOT_DIR: "data/modelnet40/modelnet40_fewshot"
  TYPE: "ModelNetFewShot"
  NUM_CLASSES: 10
  TRAIN: ("support",)
  VAL: ("target",)
  TEST: ("target",)
  FEW_SHOT:
    NUM_PER_CLASS: 1
    CROSS_NUM: 5
SOLVER:
  BASE_LR: 0.001
  MAX_EPOCH: 250
  GAMMA: 0.7
  STEPS: (20, 40, 60, 80, 100, 120, 140, 160, 180, 200, 220, 240)
TRAIN:
  BATCH_SIZE: 10
  AUGMENTATION: ("PointCloudRotate", ("PointCloudRotatePerturbation",0.06, 0.18), "PointCloudScale", "PointCloudTranslate", "PointCloudJitter",)
  LOG_PERIOD: 50
  CHECKPOINT_PERIOD: 50
  VAL_PERIOD: 1
  FREEZE: False
TEST:
  BATCH_SIZE: 10
  VIS_DIR: "@/vis_error"
  VOTE:
    ENABLE: True
    NUM_VIEW: 12
    SCORE_HEUR: ("logit",)
OUTPUT_DIR: "@/pn_fewshot_from_scratch"
AUTO_RESUME: False