TASK:
  "classification"
INPUT:
  NUM_POINTS: 1024
MODEL:
  TYPE: "POINTNET"
  POINTNET:
    DROPOUT_PROB: 0.3
    REG_WEIGHT: 0.032
DATASET:
  ROOT_DIR: "/home/rayc/Projects/shaper/data/shapenet55_h5"
  TYPE: "ShapeNet55"
  NUM_CLASSES: 55
  TRAIN: ("train",)
  VAL: ("test",)
  TEST: ("test",)
SOLVER:
  BASE_LR: 0.001
  MAX_EPOCH: 250
  GAMMA: 0.7
  STEPS: (20, 40, 60, 80, 100, 120, 140, 160, 180, 200, 220, 240)
TRAIN:
  BATCH_SIZE: 32
  AUGMENTATION: ("PointCloudRotate", "PointCloudRotatePerturbation", "PointCloudScale", "PointCloudTranslate", "PointCloudJitter",)
  LOG_PERIOD: 100
  CHECKPOINT_PERIOD: 20
  VAL_PERIOD: 1
TEST:
  BATCH_SIZE: 32
  LOG_PERIOD: 100
