TASK:
  "classification"
INPUT:
  NUM_POINTS: 1024
MODEL:
  TYPE: "PointNetFewShot"
  WEIGHT: "/home/rayc/Projects/shaper/outputs/few_shot/pointnet_fewshot_cls/model_250.pth"
  POINTNET:
    DROPOUT_PROB: 0.3
DATASET:
  ROOT_DIR: "data/modelnet40/modelnet40_fewshot"
  TYPE: "ModelNetFewShot"
  NUM_CLASSES: 10
  TRAIN: ("support",)
  VAL: ("target",)
  TEST: ("target",)
  FEW_SHOT:
    NUM_PER_CLASS: 1
    CROSS_NUM: 0
SOLVER:
  BASE_LR: 0.0003
  MAX_EPOCH: 750
  GAMMA: 0.7
  STEPS: (60, 120, 180, 240, 300, 360, 420, 480, 540, 600, 660, 720)
TRAIN:
  LOAD_PRETRAIN: True
  BATCH_SIZE: 10
  AUGMENTATION: ("PointCloudRotate", ("PointCloudRotatePerturbation",0.06, 0.18), "PointCloudScale", "PointCloudTranslate", "PointCloudJitter",)
  LOG_PERIOD: 50
  CHECKPOINT_PERIOD: 100
  VAL_PERIOD: 10
TEST:
  BATCH_SIZE: 10
  LOG_PERIOD: 50
OUTPUT_DIR: "@"