TASK:
  "classification"
INPUT:
  NUM_POINTS: 1024
MODEL:
  TYPE: "PointNetFewShot"
  WEIGHT: "/home/rayc/Projects/shaper/outputs/modelnet/few_shot/pointnet/pointnet_fewshot_cls/model_250.pth"
  POINTNET:
    DROPOUT_PROB: 0.3
    BEFORE_CHANNELS: 0
DATASET:
  ROOT_DIR: "data/modelnet40/modelnet40_fewshot"
  TYPE: "MODELNET_FEWSHOT"
  NUM_CLASSES: 10
  TRAIN: ("support",)
  VAL: ("target",)
  TEST: ("target",)
  MODELNET_FEWSHOT:
    NUM_PER_CLASS: 1
    CROSS_NUM: 0
SOLVER:
  BASE_LR: 0.001
  MAX_EPOCH: 250
  GAMMA: 0.7
  STEPS: (20, 40, 60, 80, 100, 120, 140, 160, 180, 200, 220, 240)
TRAIN:
  LOAD_PRETRAIN: True
  FREEZE_PARAMS: ('^((?!classifier).)*$',)
  BATCH_SIZE: 10
  AUGMENTATION: ("PointCloudRotate", ("PointCloudRotatePerturbation",0.06, 0.18), "PointCloudScale", "PointCloudTranslate", "PointCloudJitter",)
  LOG_PERIOD: 50
  CHECKPOINT_PERIOD: 100
  VAL_PERIOD: 150
TEST:
  BATCH_SIZE: 10
  LOG_PERIOD: 50
OUTPUT_DIR: "@"